name: CodeClimate Workflow

on:
  push:
    branches:
      - master

jobs:
  codeClimateTrigger:
    name: CodeClimate Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npm v7
        run: npm install -g npm@7
      - name: Download cc-test-reporter
        run: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - uses: actions/upload-artifact@v1
        with:
          name: test-reporter
          path: ./tmp/cc-test-reporter
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - name: Link
        run: npm run link
      - name: Bootstrap
        run: npm run bootstrap
      - name: Lerna checkLicenses
        run: npm run checkLicenses
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          TEST_SECRETS: ${{secrets.INTEGRATION_TEST_SECRETS}}
          TESTMAIL_API_KEY: ${{secrets.TESTMAIL_API_KEY}}
          TESTMAIL_NS: ${{secrets.TESTMAIL_NS}}
        with:
          coverageCommand: npm run test:coverage:codeclimate
      - name: Generate and Upload Test Coverage
        run: |
            $GITHUB_WORKSPACE/tmp/cc-test-reporter sum-coverage $GITHUB_WORKSPACE/tmp/codeclimate.*.json -p $(ls -1q $GITHUB_WORKSPACE/tmp/codeclimate.*.json | wc -l) -d -o tmp/codeclimate.total.json
            $GITHUB_WORKSPACE/tmp/cc-test-reporter upload-coverage -i $GITHUB_WORKSPACE/tmp/codeclimate.total.json
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}

